{% set version = "12.1.2" %}

package:
  name: tokei
  version: {{ version }}

source:
  url: https://github.com/XAMPPRocky/tokei/archive/v{{ version }}.tar.gz
  sha256: 81ef14ab8eaa70a68249a299f26f26eba22f342fb8e22fca463b08080f436e50

build:
  number: 0

requirements:
  build:
    - {{ compiler('rust') }}
    - cargo-bundle-licenses

test:
  commands:
    - tokei && tokei --help

about:
  home: https://tokei.rs
  license: MIT
  summary: |
    Tokei is a program that displays statistics about your code. Tokei will show
    the number of files, total lines within those files and code, comments, and
    blanks grouped by language.
  dev_url: https://github.com/XAMPPRocky/tokei
  doc_url: https://github.com/XAMPPRocky/tokei#how-to-use-tokei
  license_file:
    - LICENCE-MIT
    - THIRDPARTY.yml

extra:
  recipe-maintainers:
    - dbast
