{% set version = "9.1.1" %}

{% set native = 'm2w64-' if win else '' %}

package:
  name: tokei
  version: {{ version }}

source:
  url: https://github.com/Aaronepower/tokei/archive/v{{ version }}.tar.gz
  sha256: 3b03edf37795312a1781a5d0aa86fffea6b0bd2de3da7ea18399b43e0a2b9229

build:
  number: 0

requirements:
  build:
    - rust
    - binutils              # [linux]
    - {{native}}binutils    # [win]

test:
  commands:
    - tokei && tokei --help

about:
  home: https://tokei.rs
  license: MIT
  summary: |
    Tokei is a program that displays statistics about your code. Tokei will show
    number of files, total lines within those files and code, comments, and blanks
    grouped by language.
  dev_url: https://github.com/Aaronepower/tokei
  doc_url: https://github.com/Aaronepower/tokei#how-to-use-tokei
  license_file: 'LICENCE-MIT'

extra:
  recipe-maintainers:
    - dbast
