{% set version = "8.0.1" %}

package:
  name: tokei
  version: {{ version }}

source:
  url: https://github.com/Aaronepower/tokei/archive/v{{ version }}.tar.gz
  sha256: 9d365695e3c790747d982bf0dc598f2a65b7e51b90fa98d4f34dfef72a019e13

build:
  number: 1

requirements:
  build:
    - rust

test:
  commands:
    - tokei && tokei --help

about:
  home: https://tokei.rs
  license: MIT
  summary: |
    Tokei is a program that displays statistics about your code. Tokei will show
    number of files, total lines within those files and code, comments, and blanks
    grouped by language.
  dev_url: https://github.com/Aaronepower/tokei
  doc_url: https://github.com/Aaronepower/tokei#how-to-use-tokei
  license_file: 'LICENCE-MIT'

extra:
  recipe-maintainers:
    - dbast
