travis:
  secure:
    BINSTAR_TOKEN: ld9nNYRZTVH8IIPnhRZmQ9RwtojXRKGS4zCfwEtrUHTWQU/Ds5TMTz9kP6UuJCyRmOv9MjgAiTh2jOZpUNkvSsxpSRzkFOyz0Ts3Be+GP4bggd71GC5TKFJHAiKBGdYUrN+cguD4KhJjEFcwCD2NrMCrmR2LBxqB+31nBic90KrXtiQCxeZbPvnhfFQAUbRRNaKvGJZxqb187HzU8jhgzj7TNLEIBdjcHPY0Qcc5EvZBTCFhpbQi8zxHruBtbIPS4EiSQRXp2JT5aKSYDy4w8S3z9gQnFTC6gTQTmK3D1Zgx/298Fot4Nq6Y+QmdPXyb6UMfuXGOfqZLRJ42/WAiSSl9v3Gt8hO/IXrN2Ow47i2NenWYpepUmXIdnHCdo1xhDJDAjb0ghPiNNcT5qR9NnIqnOhHrCDnxzGGv1KfNaR73OcmQM1zvjRhgPjnt5EPg9tbCHgpPr8hmygBts0opAPVWdcj35Cuf/i4aO0pQpuo3XK1q+1TRXVyE3VpvmWaz0004GehM+Ypx3CuBX9e5YYcKGZfdTgNJ0lPk45GZ0ZVOvzfLmUP3RkLQAncZhtspM2TWyfb6CDjhLNe0/6x9Nc+hO5DZErh5PHFTls2vPeLXOtwxK1gBj9Ue5QkWxDT6yHItX+Ym8OIIK3V4f+2TCC290c9Fhz8t6YwXqhT9z/c=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
